project_name: gpgpdump
release:
  github:
    owner: spiegel-im-spiegel
    name: gpgpdump

builds:
-
  env:
  - GO111MODULE=on
  goos:
  - linux
  - darwin
  - windows
  - freebsd
  goarch:
  - amd64
  - arm
  - arm64
  main: ./
  flags:
  - -trimpath
  ldflags: -s -w -X github.com/spiegel-im-spiegel/gpgpdump/facade.Version=v{{ .Version }}
  binary: gpgpdump

archives:
-
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    freebsd: FreeBSD
  files:
  - LICENSE*
  - README*

changelog:
  sort: asc
  filters:
    exclude:
      - docs
      - typo
      - Merge pull request
      - Merge branch

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
