[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.*"

[[constraint]]
  name = "github.com/spiegel-im-spiegel/gocli"
  version = "0.8.*"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.*"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.*"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
