version: '3'

tasks:
  default:
    cmds:
      - task: prepare
      - task: test
      - task: nancy
      - task: graph

  build-all:
    desc: Build executable binary with GoReleaser.
    cmds:
      - goreleaser --snapshot --skip-publish --clean

  test:
    desc: Test and lint.
    cmds:
      - go mod verify
      - go test -shuffle on ./...
      - govulncheck ./...
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.52.1 golangci-lint run --enable gosec --timeout 10m0s ./...
    sources:
      - ./go.mod
      - '**/*.go'

  nancy:
    desc: Check vulnerability of external packages with Nancy.
    cmds:
      - depm list -j | nancy sleuth -n
    sources:
      - ./go.mod
      - '**/*.go'

  prepare:
      - go mod tidy -v -go=1.20

  clean:
    desc: Initialize module and build cache, and remake go.sum file.
    cmds:
      - rm -f ./go.sum
      - go clean -cache
      - go clean -modcache

  graph:
    desc: Make grapth of dependency modules.
    cmds:
      - depm m --dot --dot-config dot-config.toml | dot -Tpng -o ./dependency.png
    sources:
      - ./go.mod
      - '**/*.go'
    generates:
      - ./dependency.png
