version: '3'

tasks:
  default:
    cmds:
      - task: clean
      - task: test
      - task: nancy
      - task: graph

  build-all:
    desc: Build executable binary with GoReleaser.
    cmds:
      - goreleaser --snapshot --skip-publish --rm-dist

  test:
    desc: Test and lint.
    cmds:
      - go mod verify
      - go test ./...
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.40.1 golangci-lint run --enable gosec --timeout 3m0s ./...
    sources:
      - ./go.mod
      - '**/*.go'

  nancy:
    desc: Check vulnerability of external packages with Nancy.
    cmds:
      - depm list -j | docker run --rm -i sonatypecommunity/nancy:latest sleuth -n
    sources:
      - ./go.mod
      - '**/*.go'

  clean:
    desc: Initialize module and build cache, and remake go.sum file.
    cmds:
      - rm -f ./go.sum
      - go clean -cache
      - go clean -modcache
      - go mod tidy -v

  graph:
    desc: Make grapth of dependency modules.
    cmds:
      - depm m --dot --dot-config dot-config.toml | dot -Tpng -o ./dependency.png
    sources:
      - ./go.mod
      - '**/*.go'
    generates:
      - ./dependency.png
